id = "hotcrp"
name = "HotCRP"
version = "0.0.1"
schema_version = 1
authors = ["Tej Chajed"]
description = "Syntax highlighting for HotCRP offline review files."
repository = "https://github.com/tchajed/zed-hotcrp"

[grammars.hotcrp]
repository = "https://github.com/tchajed/zed-hotcrp"
commit = "8d9a6b2776ab0ecb7a7115a9e221276c84f3a35d"
