/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 12
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_template_line = 1,
  sym_paper_line = 2,
  sym_field_marker = 3,
  sym_separator_line = 4,
  sym_comment_line = 5,
  sym_score_option = 6,
  sym_field_name = 7,
  sym_blank_line = 8,
  sym_text_line = 9,
  sym_source_file = 10,
  aux_sym_source_file_repeat1 = 11,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_template_line] = "template_line",
  [sym_paper_line] = "paper_line",
  [sym_field_marker] = "field_marker",
  [sym_separator_line] = "separator_line",
  [sym_comment_line] = "comment_line",
  [sym_score_option] = "score_option",
  [sym_field_name] = "field_name",
  [sym_blank_line] = "blank_line",
  [sym_text_line] = "text_line",
  [sym_source_file] = "source_file",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_template_line] = sym_template_line,
  [sym_paper_line] = sym_paper_line,
  [sym_field_marker] = sym_field_marker,
  [sym_separator_line] = sym_separator_line,
  [sym_comment_line] = sym_comment_line,
  [sym_score_option] = sym_score_option,
  [sym_field_name] = sym_field_name,
  [sym_blank_line] = sym_blank_line,
  [sym_text_line] = sym_text_line,
  [sym_source_file] = sym_source_file,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_template_line] = {
    .visible = true,
    .named = true,
  },
  [sym_paper_line] = {
    .visible = true,
    .named = true,
  },
  [sym_field_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_separator_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_score_option] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(sym_blank_line);
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '\n', 34,
        '\r', 1,
        '#', 28,
        '=', 42,
        '\t', 35,
        ' ', 35,
        '-', 51,
        '_', 51,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(38);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(13);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_template_line);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_template_line);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_paper_line);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_paper_line);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_field_marker);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_field_marker);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == 'P') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_field_marker);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_field_marker);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_field_marker);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(18);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_field_marker);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == 'r') ADVANCE(14);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_field_marker);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_separator_line);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_separator_line);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_separator_line);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '=') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_separator_line);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '=') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_separator_line);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment_line);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_score_option);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_score_option);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_score_option);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_field_name);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_field_name);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text_line);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '_') ADVANCE(25);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == ' ' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == ' ' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(50);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(12);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(44);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(45);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(43);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '-' ||
          lookahead == '=' ||
          lookahead == '_') ADVANCE(26);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '-' ||
          lookahead == '=' ||
          lookahead == '_') ADVANCE(50);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_template_line] = ACTIONS(1),
    [sym_paper_line] = ACTIONS(1),
    [sym_field_marker] = ACTIONS(1),
    [sym_separator_line] = ACTIONS(1),
    [sym_comment_line] = ACTIONS(1),
    [sym_score_option] = ACTIONS(1),
    [sym_field_name] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_text_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_template_line] = ACTIONS(5),
    [sym_paper_line] = ACTIONS(5),
    [sym_field_marker] = ACTIONS(7),
    [sym_separator_line] = ACTIONS(7),
    [sym_comment_line] = ACTIONS(5),
    [sym_score_option] = ACTIONS(5),
    [sym_field_name] = ACTIONS(5),
    [sym_blank_line] = ACTIONS(7),
    [sym_text_line] = ACTIONS(7),
  },
  [STATE(2)] = {
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_template_line] = ACTIONS(11),
    [sym_paper_line] = ACTIONS(11),
    [sym_field_marker] = ACTIONS(13),
    [sym_separator_line] = ACTIONS(13),
    [sym_comment_line] = ACTIONS(11),
    [sym_score_option] = ACTIONS(11),
    [sym_field_name] = ACTIONS(11),
    [sym_blank_line] = ACTIONS(13),
    [sym_text_line] = ACTIONS(13),
  },
  [STATE(3)] = {
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_template_line] = ACTIONS(17),
    [sym_paper_line] = ACTIONS(17),
    [sym_field_marker] = ACTIONS(20),
    [sym_separator_line] = ACTIONS(20),
    [sym_comment_line] = ACTIONS(17),
    [sym_score_option] = ACTIONS(17),
    [sym_field_name] = ACTIONS(17),
    [sym_blank_line] = ACTIONS(20),
    [sym_text_line] = ACTIONS(20),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hotcrp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hotcrp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
